name: "Deploy Windows Zip"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

jobs:
  withoutpluginsWindowsZipDeploy:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
         (github.event_name != 'pull_request')
         || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: Deploy Windows Zip on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: windows-dist

    - name: Display structure of downloaded files
      run: dir

    # !!TODO: Turn off symlinks!!
