name: "Dockerfile"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

jobs:
  dockerfile:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
         (github.event_name != 'pull_request')
         || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: build image and run connectivity test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: docker build
      run: |
        docker build -t etherpad:test .
        docker run -d -p 9001:9001 etherpad:test
        ./src/bin/installDeps.sh
        sleep 3 # delay for startup?
        cd src && npm run test-container
