name: "In-place git pull from master"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

jobs:
  withpluginsLinux:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
         (github.event_name != 'pull_request')
         || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: Linux with Plugins
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 15]

    steps:
    - name: Checkout master repository
      uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install Etherpad plugins
      # The --legacy-peer-deps flag is required to work around a bug in npm v7:
      # https://github.com/npm/cli/issues/2199
      run: >
        npm install --no-save --legacy-peer-deps
        ep_align
        ep_author_hover
        ep_cursortrace
        ep_font_size
        ep_hash_auth
        ep_headings2
        ep_image_upload
        ep_markdown
        ep_readonly_guest
        ep_set_title_on_pad
        ep_spellcheck
        ep_subscript_and_superscript
        ep_table_of_contents

    # This must be run after installing the plugins, otherwise npm will try to
    # hoist common dependencies by removing them from src/node_modules and
    # installing them in the top-level node_modules. As of v6.14.10, npm's hoist
    # logic appears to be buggy, because it sometimes removes dependencies from
    # src/node_modules but fails to add them to the top-level node_modules. Even
    # if npm correctly hoists the dependencies, the hoisting seems to confuse
    # tools such as `npm outdated`, `npm update`, and some ESLint rules.
    - name: Install all dependencies and symlink for ep_etherpad-lite
      run: src/bin/installDeps.sh

    - name: Run the backend tests
      run: cd src && npm test

    - name: Git fetch
      run: git fetch

    - name: Checkout this branch over master
      run: git checkout "${GITHUB_SHA}"

    - name: Install all dependencies and symlink for ep_etherpad-lite
      run: src/bin/installDeps.sh

    - name: Run the backend tests
      run: cd src && npm test

    - name: Install Cypress
      run: npm install cypress -g

    - name: Run Etherpad & Test Frontend
      run: |
            node src/node/server.js &
            curl --connect-timeout 10 --max-time 20 --retry 5 --retry-delay 10 --retry-max-time 60 --retry-connrefused http://127.0.0.1:9001/p/test
            cd src/tests/frontend
            cypress run --spec cypress/integration/test.js --config-file cypress/cypress.json
